export const FETCH_USERS = 'FETCH_USERS'
export const SINGLE_USER = 'SINGLE_USER'
export const ADD_USERS = 'ADD_USERS'
export const DELETE_USER = 'DELETE_USER'
export const UPDATE_USER = 'UPDATE_USER'